### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by ghost** [ivanceras/diwata#14]
one of the dependencies is outdated and breaks during the install.
```npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.18.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm@0.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-08T05_04_13_032Z-debug.log

```

You can manually download the new update using:
wget "https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-linux.tar.gz"

**Comment by senorsmile** [comment]
any plans to upgrade to elm 0.19?

**Comment by ivanceras** [comment]
No, there is no plan to upgrade to elm 0.19
I'm planning to go on full rust.

**Comment by senorsmile** [comment]
Interesting.  Would you use something like yew for the front end? 
https://github.com/DenisKolodin/yew

**Comment by ivanceras** [comment]
Yes, I been playing with it for a while now.
