### ISSUE TITLE
Debounce search

### ISSUE THREAD

**Issue by brasilikum** [ivanceras/diwata#6]
I just quickly tried out a demo and found search to be very laggy. I guess that is because there is no debouncing - every keystroke triggers a query. It might speed up things to add a one second wait time if there are more keystrokes and then trigger the query.

I have not looked at the code but probably it would be a good idea to cancel queries if they have become obsolete (one more key added)

Other then that I found it very intersting to see and will have an eye on this project. Cheers!

**Comment by ivanceras** [comment]
The sluggishness on search has now been resolved by [disabling modification of the url](https://github.com/ivanceras/elm-webclient/commit/4ae0af3aa78e5af04c134273dea558e1f75ff5c1). This is now deployed in the demo
