### ISSUE TITLE
Spreadsheet UI mode

### ISSUE THREAD

**Issue by ajvsol** [ivanceras/diwata#7]
I found your comment [here](https://www.reddit.com/r/elm/comments/7q8m59/an_airtable_clone_that_works_with_google_drive/) on Reddit and I think it's awesome that you want to make Diwata more like Airtable seeing as people love the data entry UI for it and often use it as the backend for apps e.g. [CRM systems](https://airtable.com/universe).

This could be done via a UI toggle mode which allows more spreadsheet-like data entry, or just make adjustments to the existing UI.

Some differences would be:
- Creating field types: single line text, long text, single select etc
- Make the sidebar for tables collapsible
- Swapping from single field/column search to whole table search

Great to see the improvements you've already made towards better UI, looking forward to more to come :)

**Comment by ivanceras** [comment]
@neomodern yes, it would be a great exploration utilizing the spreadsheet UI as a way to import data into the database.
