### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by martinos** [ivanceras/diwata#8]
I tried to click on both demo link on the readme page and none of them works.

**Comment by ivanceras** [comment]
@martinos  Thanks for reporting, I usually check the demo once a week, but forgot to do it for this month. The demo server must have crashed or something. I will update the demo, come check again in a day or 2.

**Comment by ivanceras** [comment]
@martinos I have just updated the demo from the latest build. You can try it now.

**Comment by martinos** [comment]
@ivanceras, thanks it works !

**Comment by jazoom** [comment]
Looks like it's down again

**Comment by ivanceras** [comment]
I really need to remove the `panics` on wrong data type, some time. For now, I'll just redeploy this.
